POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2OTdlNWQyZTgzMjdiZDI3MjRkNWIyMjUiLCJpYXQiOjE3Njk4OTAwNTN9.gEVRP3AlnDzBh1w6CVVZCoiP45n1dKVuqAEFOuxGYQ8

{
  "title": "A horrible blog",
  "author": "Antti Anttinen ",
  "url": "https://worstblogeverrandomexampleblog123.com",
  "likes": 329
}

###

# POST define deployed url later if needed
# Content-Type: application/json

# {
#   "title": "New blog",
#   "author": "Juha Juhanen",
#   "url": "randomexampleblog123.com",
#   "likes": 5
# }