POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
  "title": "Average blog",
  "author": "Kari Karinen ",
  "url": "averagerandomexampleblog123.com",
  "likes": 6,
  "userId": "697e4d75eb71ec8fd5706ecb"
}

###

# POST define deployed url later if needed
# Content-Type: application/json

# {
#   "title": "New blog",
#   "author": "Juha Juhanen",
#   "url": "randomexampleblog123.com",
#   "likes": 5
# }